### ISSUE TITLE
Need a better document

### ISSUE THREAD

**Issue by Prayforhanluo** [rosedu1/deconvSeq#3]
Hello
I still confused how to use deconvSeq after read through the paper and went through the tutorial.
For example :   I can provide the bulk matrix file that rows indicate genes columns indicate bulk sample. Meanwhile I can provide the single cell matrix, rows indicates genes and columns indicate the single cells.  Moreover, I have already know that each column of single cell matrix represent which cell type.

I Got these information, And how to use your package to get cell fraction of each bulk sample?

Any help is appreciated.
Thanks.

**Comment by rosedu1** [comment]
Hi,
I have updated the vignette to clarify the steps. If you still run into errors, let me know.
Rose
